import type { FileDiff } from "@gitagents/forge";

const GENERATED_MARKERS = [
  "// @generated",
  "/* DO NOT EDIT */",
  "// DO NOT EDIT",
  "// auto-generated",
  "// AUTO GENERATED",
];

const LOCK_FILE_BASENAMES = new Set([
  "package-lock.json",
  "npm-shrinkwrap.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "poetry.lock",
  "Pipfile.lock",
  "Cargo.lock",
  "Gemfile.lock",
  "composer.lock",
  "go.sum",
]);

export function shouldSkipFile(
  filePath: string,
  xcoreChanged: boolean,
  diff?: FileDiff,
  fileContentSnippet?: string
): boolean {
  // Skip deleted files
  if (diff?.deletedFile) return true;

  // Skip dependency lock files (auto-generated by package managers)
  const basename = filePath.split(/[/\\]/).pop() ?? filePath;
  if (LOCK_FILE_BASENAMES.has(basename)) {
    return true;
  }

  // Always skip src-gen/
  if (filePath.includes("src-gen/") || filePath.includes("src-gen\\")) {
    return true;
  }

  // When xcore files changed, skip related src/ files (but not the xcore itself)
  if (xcoreChanged && !filePath.endsWith(".xcore")) {
    if (filePath.includes("/src/") || filePath.includes("\\src\\")) {
      return true;
    }
  }

  // Skip files with generated-file headers
  if (fileContentSnippet) {
    const firstLines = fileContentSnippet.slice(0, 500).toLowerCase();
    for (const marker of GENERATED_MARKERS) {
      if (firstLines.includes(marker.toLowerCase())) {
        return true;
      }
    }
  }

  return false;
}

export function hasXcoreChanges(diffs: FileDiff[]): boolean {
  return diffs.some((d) => d.newPath.endsWith(".xcore"));
}
